### ISSUE TITLE
Add a network card to a VM

### ISSUE THREAD

**Issue by theobromina** [chef-partners/knife-vsphere#218]
Hi!

Anyone know how to add a NIC to a VM using knife vsphere?  I've searched and couldn't find anything.  The VM template contains one NIC.  After the VM is deployed, would like to add two more for iSCSI connection.

Any help would be appreciated.

**Comment by swalberg** [comment]
Hey, we have `knife vsphere vm config` which sets properties like CPU and memory, but it doesn't add new devices. `knife vsphere vm net` get pretty close [here](https://github.com/chef-partners/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_net.rb#L41-L54), it would just need to create a new backing instead of using an existing one, and change the operation to `:add` (I think :) )

[VirtualDeviceConfigSpec](https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.vm.device.VirtualDeviceSpec.html) docs

Any interest in giving it a shot?

**Comment by mlckha** [comment]
Hi, @theobromina 
did you find a solution to your problem?
Regards,

**Comment by theobromina** [comment]
Thanks for asking, @mlckha 

No, not really.  I wound up using knife vsphere vm execute and called a PowerCLI script on a Windows server that, in turn, added the SAN NICs to the target VM.  If there is a better solution, it would be greatly appreciated.

**Comment by mlckha** [comment]
UP, if someone have a solution :+1: 

Thank's for helps
Best regards :)

**Comment by coda4096** [comment]
Any way to add network cards yet?

**Comment by swalberg** [comment]
Still no, sadly. I have some code in a script I can probably put into this gem though.

**Comment by coda4096** [comment]
I've had a shot at creating a gem for adding a NIC to a VM. 

I haven't used ruby before, so I'm not sure how to go about getting this packaged into something that Chef can install but here is my code.

https://github.com/coda4096/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_nic_add.rb

@swalberg 
Can I please have some help with testing and the pull request on this?


Thanks


~Scott

**Comment by swalberg** [comment]
I'm glad this feature will be added. Let's get your code into a pull request so we can discuss it. After that, I merge the pull request and cut a release of the gem, after which anyone installing the gem can use the command you added.

It looks like you've got your VNC feature and some testing work on your master branch, so let's try to separate this change into its own branch so that we can have a distinct PR to talk about. Here's your git history:

![knife-vsphere 2016-11-08 07-56-28](https://cloud.githubusercontent.com/assets/221368/20100303/e3ffd6be-a58a-11e6-91e3-d92b2f6fda1f.png)

The two outlined commits are the ones related to the nic change.

```
git checkout c311106   # Point your local copy to the last commit on the project
git checkout -b add_nic # Create a new local branch called `add_nic`
git cherry-pick 9d02cee 83e4430 # pick the two commits you already did and replay them on your current branch as new commits
git push origin add_nic  # push your branch to your github fork of the project
```
Go back to GitHub and you should see a bar on the page saying you recently pushed changes, along with options to compare and make a pull request. Please have a look at the comparison to make sure it's just the changes you want merged, then make a pull request.

With git and projects with more than one person, it's often easier to keep your work in a branch. Git lets you easily switch between your change sets and pull in changes from other people.

So if you need to make changes to your branch, `git checkout add_nic` to get onto your branch (if you're not already there), make your change and commit it, then `git push origin add_nic` again and GitHub will update the pull request. If you want to get back to your master branch with the VNC feature then `git checkout master`. Just remember that after this your NIC changes will be duplicated on both `master` and `add_nic`, and if you want to make changes you should only do them on `add_nic` otherwise they'll never be seen by the pull request.

**Comment by coda4096** [comment]
Thanks for your help. I have added two pull requests and all Checks have passed.

What do I do next?

**Comment by swalberg** [comment]
Thanks for putting the two PRs up. I'll look them over and try them out (and anyone else, particularly the add nic one as there was lots of interest in that feature). Might be some discussion about the code within the PR. Also, if Hound made some comments about style please try to address them and push the changes up to the same branch. Hound is an automated tool that keeps the code style consistent, which helps a project like this where there are multiple contributors.

I'm in Eastern time so it's late night here (and currently watching this crazy election coverage) so should be able to take a peek tomorrow my time.

After we're good on the code, I merge them and cut a release.

**Comment by coda4096** [comment]
this can probably be closed. anyone looking to add a Network card to a VM can now use the new command
<pre>
knife vsphere vm network add VMNAME NETWORKNAME
</pre>
