### ISSUE TITLE
Exception: NoMethodError: undefined method `identification' for #<RbVmomi::VIM::CustomizationIdentitySettings:0x007fd0b584ae30>

### ISSUE THREAD

**Issue by ZedCode** [chef-partners/knife-vsphere#223]
Hi,

After much success cloning Linux hosts, I've gone on to try the same thing with some Windows hosts. I'm getting a weird error:
```
  % knife vsphere vm clone test-clone --folder 'Templates/Windows' --template 'Win7-x86' --dest-folder 'test-cone' --resource-pool [cluster] --cvlan [vlan] --cgw [gateway] --chostname [hostname] --cips dhcp --cdnsips 'internal DNS' -VV
[...]
ERROR: knife encountered an unexpected error
This may be a bug in the 'vsphere vm clone' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `identification' for #<RbVmomi::VIM::CustomizationIdentitySettings:0x007fe23b6dd9c0>
```
I've tried to specify a `--cdomain` option as well with no luck. I'm sure this is another case of "I misunderstood the args required", but I'm not having much luck figuring it out.

Thanks!
ZC

**Comment by swalberg** [comment]
Hey ZC, sorry to hear this isn't working for you. Some of our Windows support is a bit janky and needs some love, but I don't normally do the Windows thing so it's a bit tough for me to work on.

I think you're running into #177, the best workaround we have right now is to use `--cspec` and do a lot of the customization in a server side customization specification rather than on the command line.

**Comment by ZedCode** [comment]
Hi Sean,

Thanks for the quick response! We're going to try the `--cspec` route. I am also not the "Windows guy", so this is all a bit of a struggle for me, as well :)

Thanks again!
ZC

**Comment by sumit-salunke** [comment]
Hi Sean,
knife vsphere vm clone with Linux machine, it's working fine, but I am facing issue with windows machine.

knife vsphere vm clone win2012  --template "TEMPWIN2012"  --datastore raid --cips [IP]/24 --cgw [gatway]--cmacs auto --chostname windows  -VV --start
Getting below error message.

/usr/local/rvm/gems/ruby-2.2.4/gems/knife-vsphere-1.2.17/lib/chef/knife/vsphere_vm_clone.rb:634:in `generate_clone_spec': undefined method `identification' for #<RbVmomi::VIM::CustomizationIdentitySettings:0x00000004f7f900> (NoMethodError)


I have tired with --cspec and it is working fine, but we don't want to go with it.

Please let me know, if there is any workaround for this.

**Comment by swalberg** [comment]
Hi Sumit,

In short, the number of things we have to pass to vSphere to customize a Windows machine is too many to comfortably manage with command line options, so that's why we push people to the customization specification.

The other way is to supply a plugin (`--cplugin`) that provides the same data, which would let you customize the VM through a file or a blob of data you pass on the command line (`--cplugin-data`)

https://github.com/chef-partners/knife-vsphere#plugins has an example that'll do what you're looking for. It looks for a YAML file and populates the specification from that (and some hard coded values). It should get you to where you need to be.
