### ISSUE TITLE
Add domain plugin.rb

### ISSUE THREAD

**Issue by mlckha** [chef-partners/knife-vsphere#230]
Hi, i try to add a domain to my windows plugin rb but i catch this error:

![sans titre](https://cloud.githubusercontent.com/assets/4509437/12712333/ea8ddcf6-c8c7-11e5-9242-4b33e13f8f86.png)

![a](https://cloud.githubusercontent.com/assets/4509437/12712342/fd924f62-c8c7-11e5-9533-64246915cfea.png)

thank's for help,
have a nice day,
best regards,

**Comment by swalberg** [comment]
Hi can you please paste the command line that gets you that error? Is this from our code or a plugin you're making?

I think from the [API docs](https://www.vmware.com/support/developer/vc-sdk/visdk2xpubs/ReferenceGuide/vim.vm.customization.Password.html) the password should be a `CustomizationPassword` object rather than a string. e.g.

```Ruby
RbVmobmi::VIM.CustomizationPassword.new(plainText: true, value: customization_data['password'])
```

**Comment by mlckha** [comment]
That work's, ty
