### ISSUE TITLE
knife client list - errors

### ISSUE THREAD

**Issue by bhaliti** [chef-partners/knife-vsphere#270]
[root@DP-CHEFDK01 chef]# knife client list
WARNING: No knife configuration file found
WARN: Failed to read the private key /etc/chef/client.pem: #<Errno::ENOENT: No such file or directory @ rb_sysopen - /etc/chef/client.pem>
ERROR: Your private key could not be loaded from /etc/chef/client.pem
Check your configuration file and ensure that your private key is readable
[root@DP-CHEFDK01 chef]#

**Comment by swalberg** [comment]
Hi, this looks like it's a problem with Chef / `knife` and not the `knife-vsphere` gem. Do you have a `knife.rb` file set up for the root user? Start with `knife configure`.

**Comment by bhaliti** [comment]
I am having a difficult time understanding the difference between knife.rb and client.rb. This is my workstation, I need to setup the client on the same server. 

I am sorry, I just now realized this is under vsphere.

**Comment by swalberg** [comment]
`knife.rb` is the config file for `knife`. The `client.pem` file is your user certificate for connecting to chef. For example, my `knife.rb` has

`  client_key               '/Users/sean.walberg/.chef/sean.pem'`

and I have a corresponding `sean.pem` key that I got when I set up the user on the Chef server.

It's only asking for `client.pem` because it has no other config and that's a default. Run `knife configure` to get yourself going.

FWIW I don't run my Chef commands as root because it doesn't need any local privileges on the workstation.
