### ISSUE TITLE
pools with spaces or many levels deep appear to be a problem

### ISSUE THREAD

**Issue by dhildebrandt** [chef-partners/knife-vsphere#301]
### What are you trying to do and what's not working?

I'm trying to use `knife vsphere vm find --powered-off` to identify VMs to power on
### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information

```
knife vsphere vm find -f "$dest_folder" --powered-off --pool "Name With Space/_CI/upgrade" -VV -u "$VCENTER_USER" -p "$VCENTER_PASS" --vshost "$VCENTER_HOST" --vsdc "$VCENTER_DATACENTER" --vsinsecure

DEBUG: value for config item vsphere_host: xxx.yyy.example.com
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl: 
DEBUG: value for config item vsphere_user: xxxx
DEBUG: value for config item vsphere_pass: xxx
DEBUG: value for config item vsphere_pass: xxx
DEBUG: value for config item vsphere_pass: xxx
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host: 
DEBUG: value for config item proxy_port: 
DEBUG: value for config item vsphere_dc: DC_NAME
Pool Name With Space/_CI/upgrade not found
```

I promise, the pool is there.
### Other details, such as gem version and if you're working with a Linux or Windows VM

OS is Ubuntu 14.04.5 LTS
knife-vsphere is knife-vsphere (1.2.17)
chef is not in use

**Comment by swalberg** [comment]
Hm, that's an interesting one. Currently traveling this week, will look at when I return.

Thanks for the great bug report!

Sean

**Comment by swalberg** [comment]
Having problems reproducing the issue here.

![vsphere web client 2016-10-17 17-02-31](https://cloud.githubusercontent.com/assets/221368/19455595/8eb27c26-948b-11e6-841c-cec072b66a38.png)
```
sean~/work/knife-vsphere (master)$ DC=LV bundle exec knife vsphere vm find --powered-on --pool "sean test" -f "sean_test"
VM Name: lv1devsqlm02	Folder: sean_test	State: on
sean~/work/knife-vsphere (master)$ DC=LV bundle exec knife vsphere vm find --powered-off --pool "sean test" -f "sean_test"
```

(I also have a folder called `sean_test` that has both the VMs in the picture)

Is it possible to get a screenshot of `"Name With Space/_CI/upgrade"` in the vcenter console? If "name with space" is sensitive, blank it out. I wonder if the problem relates to the sub pools or not.

**Comment by dhildebrandt** [comment]
![vsphere_web_client](https://cloud.githubusercontent.com/assets/1693961/19492311/faec93dc-952a-11e6-83b3-a57d163be0a0.png)

**Comment by dhildebrandt** [comment]
I just checked the "VMs and Template" view/namespace; while similer, its top level container is merely "Horizon" (no space).
![vsphere_web_client](https://cloud.githubusercontent.com/assets/1693961/19492621/4051365c-952c-11e6-9929-b9c919c65865.png)

**Comment by swalberg** [comment]
Thanks. I'll see what I can replicate in our environment.

**Comment by swalberg** [comment]
I was able to reproduce it here, though the spaces has nothing to do with it. When you tell it to look for `poola/subpool` it recurses through the hierarchy looking for a pool called `poola/subpool`. The `/` actually has no meaning to the code!

If you have nothing else called `upgrade` then you can pass `--pool upgrade` and it'll work, otherwise it'll stop at the first pool called `upgrade` that it finds.

I'll have to think carefully about how to fix this, as it's likely people have come to rely on the existing behavior.

**Comment by swalberg** [comment]
Hi, the latest versions of this command do away with needing to pass pools. You can now search globally now. If you had a use-case where you _need_ to filter on pool please let me know as I realize it's somewhat breaking behavior.

Going to close this as part of some cleanup, but please do re-open if you're still around.
