### ISSUE TITLE
Feature: Setup VNC

### ISSUE THREAD

**Issue by coda4096** [chef-partners/knife-vsphere#310]
Hi there. I would like to contribute to knife-vsphere but I am fairly new to ruby.

I have written a .rb to enable VNC and set the port/password. 

The problem I am having is that when I bundle exec, my sub command is not found, even though it shows in the VSPHERE COMMANDS list:

<pre>
bundle exec knife vsphere vm vncset --help
FATAL: Cannot find subcommand for: 'vsphere vm vncset --help'
Available vsphere subcommands: (for details, knife SUB-COMMAND --help)

** VSPHERE COMMANDS **
...
knife vsphere vm vncset VMNAME VNCPORT VNCPASSWORD
...
</pre>

Can anyone please point me in the right direction? Is there another file I need to edit?

[Uploading vsphere_vm_vncset.rb.zip…]()

**Comment by swalberg** [comment]
Hi Scott, thanks for putting this together. It looks like a great addition to the gem. It should auto discover but I'm wondering if it's related to the capitalization of the class name. 

Do you have this on a branch I can pull down and look at?

Thanks!

Sean

**Comment by coda4096** [comment]
I do.

https://github.com/coda4096/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_vnc_set.rb

**Comment by swalberg** [comment]
Ah, it has to do with how the command you type in is converted to the name of the class. You want to call your class `Chef::Knife::VsphereVmVncset` and it should work. Basically take the command you want the admin to type in, capitalize the words, and smash them together to get your class name. The computer doesn't care about acronyms!

What would you think of making the port and password into flags (`--vncport`, `--vncpassword` for example) rather than positional args? This would let us set defaults and people could override them in their `knife.rb`, or you could force the password to be required with a flag (see lib//chef/knife/vsphere_vm_execute.rb for examples of `options`) which would simplify the code a bit.

Your [diffs to master](https://github.com/chef-partners/knife-vsphere/compare/master...coda4096:master) also seem to have changes to `vsphere_vm_show.rb`, so please be careful when you do your pull request.

A couple of other minor things that will come up at pull request time -- We've moved to Ruby 1.9 style hashes (`foo: 'bar'`) rather than 1.8 style hashrockets ("foo" =>"bar") so please change your spec. Also please make sure to update the README with this new command, otherwise no one will know it exists!

And, as always, please let me know if you need a hand with any of the above. I'd hate to lose out on an a helpful change like this over something like formatting.

**Comment by swalberg** [comment]
PS looks like you've been on GitHub for a bit but this is your first contribution. Congratulations! And please don't hesitate to ask for help; there are no silly questions especially when `git` is involved.

**Comment by coda4096** [comment]
Thanks! 

That seems to have worked.

I will make the VNC port/password into flags as you recommended.

I undid the changes I made to **vsphere_vm_show.rb** (was some testing) this should now be the original file.

Thanks again, I will no doubt need your help in the future as I am working on few things in knife-vsphere...

**Comment by swalberg** [comment]
Awesome! Please look at joining the [VMWare {Code} Slack](https://code.vmware.com/slack/)... I'm on there as are some people from Chef.

I'll also close this issue as the original question seems to be resolved. Feel free to re-open it or create a new one if anything else comes up.
