### ISSUE TITLE
Feature: list networks on a vm and delete networks from a vm

### ISSUE THREAD

**Issue by coda4096** [chef-partners/knife-vsphere#317]
I've been using the new **vm network add** command and it works great but I also need to be able to list and delete the networks on a VM.

I can have a go at creating these commands but I need some sample code to work with. Listing networks and deleting networks.

Can anyone help with sample code?

**Comment by coda4096** [comment]
I have done the list networks, still need sample of delete a network from vm

**Comment by swalberg** [comment]
Hey, this'll be a great addition. You'll want to do a `ReconfigVM_Task` with a [spec](https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.vm.ConfigSpec.html) pointing to a [VirtualDeviceSpec](https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.vm.device.VirtualDeviceSpec.html) with the device set to the network card and the `operation` set to `remove`.

I'm not sure how you refer to the [device](https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.vm.device.VirtualDevice.html) -- the `key` is required, and if you can get that out of the existing machine info that would be good, otherwise you might have to fill in the backing.

**Comment by coda4096** [comment]
Can I please have some help with listing the name of the networks connected to a NIC?

This code lists the NICs connected to a VM. How do you find the networks connected to the NIC?
<pre>
vm.config.hardware.device.each.grep(RbVmomi::VIM::VirtualEthernetCard) do |a|
      backing = a.backing
      key = a.key
      puts "#{ui.color('NIC', :cyan)}: #{a.deviceInfo.label}"
    end
</pre>

I think I need something like this code (lists networks for a dc):
<pre>
dc.network.each do |network|
  puts "#{ui.color('VLAN', :cyan)}: #{network.name}"
end
</pre>

**Comment by coda4096** [comment]
To be more specific:
> delete the networks on a VM.
should be 

> delete a NIC from a VM

**Comment by coda4096** [comment]
cool, these are ready

**Comment by coda4096** [comment]
these work nicely
