### ISSUE TITLE
Unable to set static IP , on NIC eno16777984.

### ISSUE THREAD

**Issue by sethas** [chef-partners/knife-vsphere#403]
### Versions:

* Version of knife-vsphere: latest
* Version of chef: 12.19.36

### Platform Details

* Version of vSphere: 6
* Version of ESXi: 

### Scenario:
knife vsphere vm clone testin-01 --folder 'Templates' --dest-folder 'test' --template 'TEST2-CentOS72' --datastore testds01 --chostname testin-01 --cips 10.2.3.4 --cgw 10.2.3.1

### Expected Result:

I expect the /etc/sysconfig/network-scripts/ifcfg-eno16777984 file to be overwritten with the ip and gateway provided on commandline. 
However this is not happening  . 

All our VMs are on the eno16777984 NIC. just for fun sake I tried eth0, but that dint overwrite the file. 

Am I missing something . Please help. 

### Actual Result:

No errors, my template clones to the VM , with the default settings from the template.

**Comment by swalberg** [comment]
Hi, do you have the vsphere agent running on that template? [This guide](https://github.com/chef-partners/knife-vsphere/wiki/Making-a-template-for-cloning) gives some advice on what's needed on the template for customization to work.

**Comment by sethas** [comment]
That helped. Perl was not installed on my template. 

However the default file it created is ifcfg-ens160. I tried to set prereq configurations on the template , but my knife-vsphere overwrote them 

Is it possible to set the DEVICE , DNS1, DNS2 , DOMAIN, NAME , TYPE, PEERDNS, PEERROUTES once the vm is cloned , or during build

**Comment by swalberg** [comment]
Hi, yes some of that can be set. Look at `--cdns`, `--cdomain`, and `--chostname` to set the name related ones. If you want DCHP rather than static addressing, use `--cips dhcp`.

We don't write those files directly. This gem sets up some _customizations_ that are sent to vsphere at the same time as the template is cloned, vsphere sends those to the agent on the template once it's booted, and the agent configures the box according to the particulars of the distribution. As there are often a couple of ways to do things, such as setting the hostname, you're stuck with what the fine folks at VMWare have determined is appropriate.

If you do need to set routes there are some other files that get read during the network initialization, for example `/etc/sysconfig/network-scripts/route-ens160` that can be templated with Chef after the box has converged.

**Comment by sethas** [comment]
Although not alligned to this issue
Is there a way I can 'sed' & edit or run any bash command on the file once cloned using vmware tools.

**Comment by swalberg** [comment]
There's `knife vsphere vm execute` which is somewhat limited by the API as to what it can do. But if your template had a file you wanted to run that had all the magic, you could run that.

**Comment by sethas** [comment]
Understood. Thats perfect. 

Thank you so much
