### ISSUE TITLE
Multinode Config file for knife vsphere vm clone

### ISSUE THREAD

**Issue by oleg-filiutsich** [chef-partners/knife-vsphere#439]
The tool have some functional for use config file parameters with multiply host some like
```
# Config json
"NewNode": {"template": "UbuntuTemplate",
"cspec" : "StaticSpec",
    "cips": ["192.168.0.99/24","192.168.1.99/24"]
}
```
and use it for provision and bootstrap multinode in knife vsphere vm clone like

```
 vsphere vm clone -config config.json
```
???

**Comment by swalberg** [comment]
Hi Oleg, we don't have anything exactly like that. It's possible to do with a [plugin](https://github.com/chef-partners/knife-vsphere#plugins), for example [this one](https://github.com/chef-partners/knife-vsphere/wiki/Sample-plugin-to-do-unattended-Windows-installations) does something similar with Windows installations.

If everything you do is already available as a command line option, it may be faster to wrap `knife vsphere vm clone` with a script to do what you want rather than making a plugin. For example, I rarely call this gem directly when cloning, I have a shell script that passes some defaults and does some sanity checking for my particular environment, before calling `knife vsphere vm clone`.
